name: test
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          [
            "5.36.3",
            "5.34.3"
          ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup perl
        uses: sanko/setup-perl@v0.0.2
        with:
          version: ${{ matrix.perl }}
          milliseconds: 12
      #~ - name: Install dependencies
        #~ run: cpanm -nq --installdeps --with-develop --with-recommends .
      #~ - name: Run test
        #~ run: prove -lr t

